redshifttransform:
  outputs:

    dev:
      dbname: imdb
      host: ex-complete-default.cxpzhmknsoiv.us-east-1.redshift.amazonaws.com
      password: redshift
      port: 5439
      schema: imdb
      threads: 1
      type: redshift
      user: redshift

    prod:
      dbname: imdb
      host: ex-complete-default.cxpzhmknsoiv.us-east-1.redshift.amazonaws.com
      password: redshift
      port: 5439
      schema: imdb
      threads: 1
      type: redshift
      user: redshift

  target: dev